# Generated by Django 5.0.4 on 2024-05-05 10:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for patient', primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Sphere', 'Sphere'), ('Box', 'Box'), ('Cylinder', 'Cylinder')], max_length=8)),
                ('color', models.CharField(help_text='hex', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='PatientColonscropyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Checkdate', models.DateTimeField(auto_now_add=True)),
                ('diagnosis', models.TextField(help_text='Enter the dignosis', max_length=1000)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Focus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foucus_id', models.CharField(max_length=10, verbose_name='focus ID')),
                ('focus_name', models.CharField(max_length=20)),
                ('focus_diagnosis', models.TextField(help_text='Enter the dignosis', max_length=100)),
                ('size', models.CharField(blank=True, max_length=6)),
                ('position', models.CharField(choices=[('a', '升結腸'), ('d', '降結腸'), ('c', '橫結腸')], max_length=1)),
                ('mark', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='images')),
                ('treatment_image', models.ImageField(blank=True, upload_to='')),
                ('colonscropyRecord', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.patientcolonscropyrecord')),
            ],
        ),
    ]
