# Generated by Django 5.0.4 on 2024-05-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_alter_patientcolonscropyrecord_checkdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focus',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
