# Generated by Django 5.0.4 on 2024-05-20 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_alter_focus_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='focus',
            old_name='foucus_id',
            new_name='focus_id',
        ),
    ]
