# Generated by Django 5.0.4 on 2024-06-20 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_delete_shape_alter_focus_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColonCaseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(blank=True, max_length=20, null=True)),
                ('focus_diagnosis', models.TextField(blank=True, max_length=100, null=True)),
                ('focus_name', models.CharField(blank=True, max_length=20, null=True)),
                ('patient_name', models.CharField(blank=True, max_length=10, null=True)),
                ('patient_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='病歷號')),
                ('checkdate', models.DateField(blank=True, null=True, verbose_name='檢查日期')),
                ('position', models.CharField(blank=True, choices=[('a', '升結腸'), ('d', '降結腸'), ('c', '橫結腸'), ('C', '盲腸'), ('s', '乙狀結腸'), ('r', '直腸')], max_length=1, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('treatment_image', models.ImageField(blank=True, upload_to='')),
                ('comorbidity', models.CharField(blank=True, max_length=255, null=True)),
                ('sedation', models.CharField(blank=True, max_length=255, null=True)),
                ('medication', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('reach_cecum_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('insertion_time', models.DurationField(blank=True, null=True)),
                ('withdraw_time', models.DurationField(blank=True, null=True)),
                ('insertion_level', models.CharField(blank=True, max_length=255, null=True)),
                ('cleansing_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('colon_cleansing_level', models.CharField(blank=True, max_length=255, null=True)),
                ('complication', models.CharField(blank=True, max_length=255, null=True)),
                ('count_of_specimen', models.IntegerField(blank=True, null=True)),
                ('findings_endoscopic_diagnosis', models.TextField(blank=True, null=True)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('others', models.TextField(blank=True, null=True)),
                ('impression', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
