# Generated by Django 5.0.4 on 2024-06-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_coloncasereport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientcolonscropyrecord',
            name='patient',
        ),
        migrations.AlterField(
            model_name='coloncasereport',
            name='position',
            field=models.CharField(blank=True, choices=[('a', '升結腸'), ('d', '降結腸'), ('t', '橫結腸'), ('c', '盲腸'), ('s', '乙狀結腸'), ('r', '直腸')], max_length=1, null=True),
        ),
        migrations.DeleteModel(
            name='Focus',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='PatientColonscropyRecord',
        ),
    ]
