# Generated by Django 5.0.4 on 2024-06-26 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_remove_patientcolonscropyrecord_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coloncasereport',
            name='treatment_image',
            field=models.ImageField(blank=True, upload_to='treatment_image'),
        ),
    ]
