# Generated by Django 5.0.4 on 2024-07-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_alter_coloncasereport_treatment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coloncasereport',
            name='treatment_image',
            field=models.ImageField(blank=True, upload_to='treatment_image/'),
        ),
    ]
