# Generated by Django 5.0.4 on 2024-07-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0011_alter_coloncasereport_treatment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='coloncasereport',
            name='size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='coloncasereport',
            name='position',
            field=models.CharField(blank=True, choices=[('an', '近升結腸'), ('af', '遠升結腸'), ('dn', '近降結腸'), ('df', '遠降結腸'), ('tn', '近橫結腸'), ('tf', '遠橫結腸'), ('c', '盲腸'), ('s', '乙狀結腸'), ('r', '直腸')], max_length=2, null=True),
        ),
    ]
